### ISSUE TITLE
TypeError: Cannot read property 'NextShardIterator' of undefined

### ISSUE THREAD

**Issue by zbyte64** [mhart/kinesis#19] opened 2015-10-02 17:24 UTC
Got the following stack trace/error:

```
/home/jason/Repos/webin8-bot/node_modules/kinesis/index.js:161
    if (res.NextShardIterator == null) {
           ^
TypeError: Cannot read property 'NextShardIterator' of undefined
    at /home/jason/Repos/webin8-bot/node_modules/kinesis/index.js:161:12
    at f (/home/jason/Repos/webin8-bot/node_modules/kinesis/node_modules/once/once.js:17:25)
    at /home/jason/Repos/webin8-bot/node_modules/kinesis/index.js:395:16
    at IncomingMessage.<anonymous> (/home/jason/Repos/webin8-bot/node_modules/kinesis/index.js:344:20)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

This is on a stream where I am only reading events.

**Comment by mhart** [comment] 2015-10-02 18:04
Woah, that's weird – that means the response is undefined.

Ah, I guess it's probably this: https://github.com/mhart/kinesis/blob/master/index.js#L395

I should construct an error there if we've reached the max number of retries

**Comment by mhart** [comment] 2015-10-02 18:07
Although... that doesn't really make sense either because `err` wouldn't be null in that case.

So it's come from here: https://github.com/mhart/kinesis/blob/master/index.js#L344

So somehow the JSON is parsing as null? That doesn't make sense either.

Can you reproduce easily?

**Comment by mhart** [comment] 2015-10-02 18:11
Or it could be that Kinesis has returned an empty response somehow, so this line is false: https://github.com/mhart/kinesis/blob/master/index.js#L340

But it would be weird to return an empty response with a 200.

Any more info you can give (a reproducible case, Node.js version, etc) would help track it down hopefully.

**Comment by zbyte64** [comment] 2015-10-02 19:51
This was just a one off error, can't really reproduce. I have been running this script for weeks and this is the first I've seen it.

**Comment by mhart** [comment] 2015-10-02 19:52
Tricky. Ok, thanks. I'll have a bit more of a think about it.

**Comment by zbyte64** [comment] 2015-10-02 19:52
node v0.12.7 and the latest kinesis 1.2.2

**Comment by mhart** [comment] 2019-01-03 15:56
Going to close this – if there's an easy way to reproduce, happy to reopen

**Closed by mhart** 2019-01-03 15:56 UTC
